name: Test Project
permissions:
  actions: write
  contents: read
on: 
  push:
   branches:
    - master
    - develop
  pull_request:
   branches:
    - master
    - develop
  workflow_dispatch:
    inputs:
      testType:
        description: 'Select test type (all, ui, api)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ui
          - api
      headless:
          description: 'Run in headless mode?'
          required: false
          default: true
          type: boolean    
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD}}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install   
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Generate dist (simulated)
        run: |
          mkdir -p dist
          echo "Hello from dist" > dist/index.html
      - name: Run ui tests
        run: npx playwright test e2e/tests/ui
      - name: Run api tests
        run: npx playwright test e2e/tests/api
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
            name: test-report
            path: test.json
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls -R
  deploy: 
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Check dist folder
        run: ls -la ./dist
      - name: Output contents
        run: ls -R
      - name: Deploy
        run: echo "Deploying..."
